### ISSUE TITLE
_wireguard_config.py assumes sysconfdir=/etc

### ISSUE THREAD

**Issue by rtollert** [ni/nilrt-snac#20]
Merely running `make install` is more or less guaranteed to generate a broken package, because `prefix ?= /usr/local` and `sysconfdir ?= $(prefix)/etc`, i.e. by default, `$(sysconfdir)` expands to `/usr/local/etc`. But `_wireguard_config.py` explicitly refers to a path under `/etc`, which will fail unless `sysconfdir=etc`.

Technically I suppose this qualifies as technical debt, since the ipks work, and if you follow the instructions in the README to the letter, it will work too. Still.

**Comment by amstewart** [comment]
The core of this issue is really that the [Makefile](https://github.com/ni/nilrt-snac/blob/ac2c1d3f603b2f7b0be72cdf8515cceb3b64523e/Makefile#L97) installs wireguard configuration files to `${DESTDIR}${sysconfdir}/wireguard` and `${DESTDIR}${sysconfdir}/init.d`, despite neither wireguard-tools nor sysvinit searching any conf directories other than `/etc`. So the installation paths in the Makefile should just be changed over to `${DESTDIR}/etc/wireguard` (or similar for init.d).
